# Generated by Django 3.2.9 on 2021-12-24 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_auto_20211201_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='size',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='Размер'),
        ),
    ]
